# Generated by Django 5.2.4 on 2025-07-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_branch_semester_exam_examtiming_invigilator_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
