# Generated by Django 5.2.4 on 2025-07-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_examresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='examtiming',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='exam',
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='student',
        ),
        migrations.RemoveField(
            model_name='invigilator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('invigilator', 'Invigilator')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='ExamTiming',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='ExamResult',
        ),
        migrations.DeleteModel(
            name='Invigilator',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
