# Generated by Django 5.2.4 on 2025-07-17 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_exam_alter_profile_otp_secret_newexamresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='otp_secret',
        ),
        migrations.AddField(
            model_name='newexamresult',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='secret_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newexamresult',
            name='score',
            field=models.IntegerField(),
        ),
    ]
